# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5WkbivQcTEPsWWAmnW5yoD9_VVHPWZo
"""

# app.py
from flask import Flask, request, jsonify
from flask_cors import CORS
from sentence_transformers import SentenceTransformer

app = Flask(__name__)
CORS(app)

# 使用512維模型 (確保維度正確)
model = SentenceTransformer('distiluse-base-multilingual-cased-v1')

@app.route('/generate_embedding', methods=['POST'])
def generate_embedding():
    data = request.json
    text = data['text']
    embedding = model.encode(text).tolist()
    return jsonify({"embedding": embedding})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)